# Name and metadata of your task
task_name: 'Free Token Task!'
author: 'Soma'
description: "This task submits 'Hello World' to confirm that your node is online. You will earn up to 50 KOII in one day. This task will use around 1.5gb of your RAM."
repositoryUrl: 'https://github.com/koii-network/task-examples'
imageUrl: 'https://bafybeiaxjv3wnyeuakhvpeah5aiuomswegn2qfk47w6hrd475gkibflhvy.ipfs.w3s.link/image.png'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 2000

audit_window: 750
submission_window: 750

# Amounts in KOII
minimum_stake_amount: 1.5

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 100000

bounty_amount_per_round: 50000

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 2

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

requirementsTags:
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

# OPTIONAL variables variables for creating task / REQUIRED variables for update task

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: '6WLjePiE9TuTTno3vKiN42RsmqF7xVtSzsJNwHj9Svxg'

# Provide the description for changes made in new version of task
migrationDescription: 'Release new Free Token Task. Increase rewad to 3 KOII per round. 50 KOII per day.'
